services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - contracts

  contracts:
    image: ghcr.io/foundry-rs/foundry:latest
    working_dir: /app
    volumes:
      - ./contracts:/app
    command: ["forge", "build"]
    environment:
      - FOUNDRY_PROFILE=default

  # mobile-dev:
  #   build:
  #     context: ./mobile
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "19000:19000"
  #     - "19001:19001"
  #     - "19002:19002"
  #   environment:
  #     - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
  #   volumes:
  #     - ./mobile:/app
  #     - /app/node_modules
  #   command: ["npm", "start"]

networks:
  default:
    name: chilipocket-network